[project]
name = "ccsds-tm-decom"
version = "0.1.0"
description = "CCSDS TM frame decomutator"
authors = [
    {name = "Benoit Hassan"}
]
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "asyncpg (>=0.31.0,<0.32.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "testcontainers[postgres] (>=4.15.0,<5.0.0)"
]

[tool.poetry]
packages = [{include = "ccsds_tm_decom", from = "src"}]

[project.scripts]
ccsds-tm-decom = "ccsds_tm_decom.main:main"